### ISSUE TITLE
screenshot1

### ISSUE THREAD

**Issue by yangli2014** [yangli2014/bffwith_akka#1]
![Screen Shot 2022-09-15 at 4 26 11 PM](https://user-images.githubusercontent.com/9009178/190502853-3bc928cb-95c6-42b1-b721-eebb495059d8.png)

![bff_akka](https://user-images.githubusercontent.com/9009178/190507387-e660102e-0a29-4ced-a33c-e0a24360000c.png)

![bff_spring](https://user-images.githubusercontent.com/9009178/190508513-de585997-e5ad-4249-9b4d-7872ebdc98c9.png)

![bff_spring_error](https://user-images.githubusercontent.com/9009178/190508693-0ff2e888-7537-464f-9773-469a4f756a3d.png)

**Comment by denkonakov** [comment]
I think we can move this one to closed, right?
